[project]
name = "spx-info"
version = "0.1.0"
description = "Investigating the S&P 500"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "yfinance"
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "uv>=0.7.2",
]
